# Generated by Django 3.2.9 on 2021-11-23 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_transactions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
