# Generated by Django 3.2.9 on 2021-11-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_auto_20211123_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.account'),
        ),
    ]
