# Generated by Django 3.2.9 on 2021-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0006_transactions_txntpe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
