# Generated by Django 3.2.9 on 2021-12-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0007_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.accounttype'),
        ),
    ]
