# Generated by Django 3.2.9 on 2021-12-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0010_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTSL_Dispute_Adjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('ref_no', models.CharField(max_length=256)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Description',
            new_name='Description_NTSL',
        ),
        migrations.CreateModel(
            name='NTSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nooftxns', models.IntegerField()),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.description_ntsl')),
            ],
        ),
    ]
