# Generated by Django 3.2.9 on 2021-12-15 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0011_auto_20211214_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntsl',
            name='cycle',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ntsl',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
