# Generated by Django 3.2.9 on 2021-12-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0012_auto_20211215_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ntsl',
            unique_together={('date', 'cycle')},
        ),
    ]
