# Generated by Django 3.2.9 on 2021-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0016_rgcs_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgcs',
            name='customerCompensationCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='customerCompensationDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='finalNet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='finalSumCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='finalSumDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='intFeeAmtCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='intFeeAmtDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='memIncFeeAmtCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='memIncFeeAmtDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='othFeeAmtCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='othFeeAmtDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='othFeeGstCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='othFeeGstDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='setAmtCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='setAmtDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='setCCY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='txnAmtCr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='txnAmtDr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='txnCCY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='txnCount',
            field=models.IntegerField(null=True),
        ),
    ]
