# Generated by Django 3.2.9 on 2021-12-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0020_auto_20211220_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-txnNo']},
        ),
    ]
