# Generated by Django 3.2.9 on 2021-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0021_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipandSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('finalAmount', models.FloatField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
