# Generated by Django 3.2.9 on 2021-12-22 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0022_tipandsurcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipandsurcharge',
            name='cycle',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
