# Generated by Django 3.2.9 on 2021-12-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0023_tipandsurcharge_cycle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipandsurcharge',
            unique_together={('date', 'cycle')},
        ),
    ]
