# Generated by Django 3.2.9 on 2021-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0025_ntsl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgcs',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
