# Generated by Django 3.2.9 on 2021-12-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0026_alter_rgcs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgcs',
            name='postingstatus',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rgcs',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.status'),
        ),
    ]
