# Generated by Django 3.2.9 on 2021-12-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0027_auto_20211222_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('adjustmentDate', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
