# Generated by Django 3.2.9 on 2021-12-23 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0028_pendingentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingentries',
            old_name='amount',
            new_name='creditAmount',
        ),
        migrations.AddField(
            model_name='pendingentries',
            name='debitAmount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingentries',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
