# Generated by Django 3.2.9 on 2021-12-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0030_alter_pendingentries_adjustmentdate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rgcs',
            unique_together={('date', 'cycle', 'inwardOutward', 'status', 'transactionCycle', 'transactionType', 'channel')},
        ),
    ]
